name: Drone Config Compliance Validation
on:
  push:
    paths:
      - 'src/lib/plugins/drone-config/**'
  pull_request:
    paths:
      - 'src/lib/plugins/drone-config/**'
  schedule:
    - cron: '0 */2 * * *' # Every 2 hours

jobs:
  compliance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: NASA JPL Compliance Check
        run: |
          chmod +x src/lib/plugins/drone-config/validation/continuous-validation.sh
          ./src/lib/plugins/drone-config/validation/continuous-validation.sh

      - name: TypeScript Strict Check
        run: npx tsc --noEmit --strict

      - name: Safety Tests
        run: npm run test -- --grep "safety|emergency" || true

      - name: Test Coverage
        run: npm run test:coverage -- src/lib/plugins/drone-config

      - name: Generate Report
        if: always()
        run: |
          echo "## Drone Config Validation Report" > validation-report.md
          echo "Date: $(date)" >> validation-report.md
          echo "" >> validation-report.md
          ./src/lib/plugins/drone-config/validation/continuous-validation.sh >> validation-report.md 2>&1 || true

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: validation-report
          path: validation-report.md
